spring:
  config:
    activate:
      on-profile: dev
  datasource:
    write:
      jdbc-url: jdbc:mysql://RDB_ADDRESS:3306/mydatabase?autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      username: admin
      password: adminpass
      minimum-idle: 1
      maximum-pool-size: 2
      useServerPrepStmts: true
    read:
      jdbc-url: jdbc:mysql://RDB_ADDRESS:3306/mydatabase?autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      username: admin
      password: adminpass
      minimum-idle: 1
      maximum-pool-size: 2
      useServerPrepStmts: true
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: "classpath:db/migration"
    validateMigrationNaming: true
server:
  error:
    include-exception: false
    include-stacktrace: never
    path: '/auth/error'
    whitelabel:
      enabled: false
  port: 38080
redis:
  host: dev-an2-elc-cr-care-os2hpl.serverless.apn2.cache.amazonaws.com
  port: 6379
  auth: false
  authentication:
    database: 0
  user:
    database: 1
  noti:
    database: 5
  sso:
    database: 6
  type: STANDARD
aws:
  ses:
    aws_key_id: AWS_KEY_ID
    aws_key_password: AWS_KEY_PASSWORD
    host: SES_SMT
    port: 587
    configuration: AWS_SES_CONFIGURATION
    from: FROM_EMAIL_ADDRESS
    fromName: FROM_EMAIL_NAME
  sns:
    ec2policy: false
    credentials:
      access-key: AWS_ACCESS_KEY
      secret-key: AWS_SECRET_KEY
ssh:
  use: false
jwt:
  secret: mysecret
email:
  check:
    page: email-dev
  exceed_cnt: 1000
sms:
  exceed_cnt: 1000
